name: MCG Vertretungsplan Parser Add-on
version: 1.0
slug: pyrser
description: Ein Skript welches den Vertretungsplan des MCG-Dresden für bestimmte klassen in einem Strinarray darstellt.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  variable: ""
schema:
  variable:
    type: string
    required: true